export const polymarketAaveStakingVaultAbi = [
    { type: 'function', inputs: [], name: 'NO_INDEX', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'NO_INDEX_SET',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'PARENT_COLLECTION_ID',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'YES_INDEX', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'YES_INDEX_SET',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'aToken',
        outputs: [{ name: '', internalType: 'contract IAToken', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'aavePool',
        outputs: [{ name: '', internalType: 'contract IPool', type: 'address' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'conditionId', outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'ctf',
        outputs: [{ name: '', internalType: 'contract IConditionalTokens', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'dataProvider',
        outputs: [{ name: '', internalType: 'contract IPoolDataProvider', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: 'isYes', internalType: 'bool', type: 'bool' },
            { name: 'amount', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'deposit',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'depositLimit',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'finalizationTime',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'finalizeGlobalScore', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'finalizeMarket', outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'finalizeUserScore',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    { type: 'function', inputs: [], name: 'finalized', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getBalance',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getCurrentApy',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getCurrentSupplyAndLimit',
        outputs: [
            { name: 'supplyYes', internalType: 'uint256', type: 'uint256' },
            { name: 'supplyNo', internalType: 'uint256', type: 'uint256' },
            { name: 'supplyLimit', internalType: 'uint256', type: 'uint256' },
            { name: 'strategySupply', internalType: 'uint256', type: 'uint256' },
            { name: 'strategyLimit', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getCurrentUserYield',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getCurrentYieldBreakdown',
        outputs: [
            { name: 'estTotalYield', internalType: 'uint256', type: 'uint256' },
            { name: 'estUserYield', internalType: 'uint256', type: 'uint256' },
            { name: 'estProtocolYield', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getGlobalScore',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getScore',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getTvlUsd',
        outputs: [
            { name: 'onHandUsd', internalType: 'uint256', type: 'uint256' },
            { name: 'inStrategyUsd', internalType: 'uint256', type: 'uint256' },
            { name: 'convertibleUsd', internalType: 'uint256', type: 'uint256' },
            { name: 'tvlUsd', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getUserBalances',
        outputs: [
            { name: 'userYes_', internalType: 'uint256', type: 'uint256' },
            { name: 'userNo_', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getUserState',
        outputs: [
            { name: 'balance', internalType: 'uint256', type: 'uint256' },
            { name: 'lastUpdated', internalType: 'uint256', type: 'uint256' },
            { name: 'cumulativeScore', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getVaultPairedPrincipalUsd',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getVaultUnpaired',
        outputs: [
            { name: 'yes_', internalType: 'uint256', type: 'uint256' },
            { name: 'no_', internalType: 'uint256', type: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'globalLastBalance',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'globalLastUpdated',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'globalScore', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [{ name: 'receiver', internalType: 'address', type: 'address' }],
        name: 'harvestProtocolYield',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    { type: 'function', inputs: [], name: 'harvestYield', outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        inputs: [
            { name: '_protocolFeeBps', internalType: 'uint256', type: 'uint256' },
            { name: '_underlying', internalType: 'address', type: 'address' },
            { name: '_ctf', internalType: 'address', type: 'address' },
            { name: '_conditionId', internalType: 'bytes32', type: 'bytes32' },
            { name: '_negRiskAdapter', internalType: 'address', type: 'address' },
            { name: '_negRisk', internalType: 'bool', type: 'bool' },
            { name: '_collateral', internalType: 'address', type: 'address' },
            { name: '_checkResolved', internalType: 'bool', type: 'bool' },
            { name: '_aavePool', internalType: 'address', type: 'address' },
            { name: '_aaveDataProv', internalType: 'address', type: 'address' },
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    { type: 'function', inputs: [], name: 'leftoverUsd', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'negRisk', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'negRiskAdapter',
        outputs: [{ name: '', internalType: 'contract INegRiskAdapter', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'noPositionId',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: '', internalType: 'address', type: 'address' },
            { name: '', internalType: 'address', type: 'address' },
            { name: '', internalType: 'uint256[]', type: 'uint256[]' },
            { name: '', internalType: 'uint256[]', type: 'uint256[]' },
            { name: '', internalType: 'bytes', type: 'bytes' },
        ],
        name: 'onERC1155BatchReceived',
        outputs: [{ name: '', internalType: 'bytes4', type: 'bytes4' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '', internalType: 'address', type: 'address' },
            { name: '', internalType: 'address', type: 'address' },
            { name: '', internalType: 'uint256', type: 'uint256' },
            { name: '', internalType: 'uint256', type: 'uint256' },
            { name: '', internalType: 'bytes', type: 'bytes' },
        ],
        name: 'onERC1155Received',
        outputs: [{ name: '', internalType: 'bytes4', type: 'bytes4' }],
        stateMutability: 'nonpayable',
    },
    { type: 'function', inputs: [], name: 'owner', outputs: [{ name: '', internalType: 'address', type: 'address' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'pairedUsdPrincipal',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'pauseAll', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'pauseDeposits', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'pauseUnlockYield', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'pauseWithdrawals', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'pausedAll', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'pausedDeposits', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'pausedUnlockYield', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'pausedWithdrawals', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'polymarketCollateral',
        outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'protocolFeeBps',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'protocolYield',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'protocolYieldHarvested',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'redeemWinningForUsd', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        inputs: [{ name: 'newLimit', internalType: 'uint256', type: 'uint256' }],
        name: 'setDepositLimit',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
        name: 'supportsInterface',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'totalUserYes',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'totalYield', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'underlyingUsd',
        outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'unlockYield', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'unlockedUsd', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'unlocking', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'unpairedNo', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'unpairedYes', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', inputs: [], name: 'unpauseAll', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'unpauseDeposits', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'unpauseUnlockYield', outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', inputs: [], name: 'unpauseWithdrawals', outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        inputs: [
            { name: 'supplyDelta', internalType: 'uint256', type: 'uint256' },
            { name: 'increase', internalType: 'bool', type: 'bool' },
        ],
        name: 'updateGlobalScore',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: 'user', internalType: 'address', type: 'address' },
            { name: 'balanceDelta', internalType: 'uint256', type: 'uint256' },
            { name: 'increase', internalType: 'bool', type: 'bool' },
        ],
        name: 'updateScore',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    { type: 'function', inputs: [], name: 'userYield', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }], stateMutability: 'view' },
    {
        type: 'function',
        inputs: [],
        name: 'winningPosition',
        outputs: [{ name: '', internalType: 'enum RobinStakingVault.WinningPosition', type: 'uint8' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: 'yesAmount', internalType: 'uint256', type: 'uint256' },
            { name: 'noAmount', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'yesPositionId',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', inputs: [], name: 'yieldUnlocked', outputs: [{ name: '', internalType: 'bool', type: 'bool' }], stateMutability: 'view' },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'user', internalType: 'address', type: 'address', indexed: true },
            { name: 'isYes', internalType: 'bool', type: 'bool', indexed: false },
            { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'Deposited',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'finalizationTime', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'globalScore', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'GlobalFinalized',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'receiver', internalType: 'address', type: 'address', indexed: true },
            { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'HarvestedProtocolYield',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'user', internalType: 'address', type: 'address', indexed: true },
            { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'HarvestedYield',
    },
    { type: 'event', anonymous: false, inputs: [{ name: 'version', internalType: 'uint64', type: 'uint64', indexed: false }], name: 'Initialized' },
    {
        type: 'event',
        anonymous: false,
        inputs: [{ name: 'winningPosition', internalType: 'enum RobinStakingVault.WinningPosition', type: 'uint8', indexed: false }],
        name: 'MarketFinalized',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'previousOwner', internalType: 'address', type: 'address', indexed: true },
            { name: 'newOwner', internalType: 'address', type: 'address', indexed: true },
        ],
        name: 'OwnershipTransferred',
    },
    { type: 'event', anonymous: false, inputs: [{ name: 'paused', internalType: 'bool', type: 'bool', indexed: false }], name: 'PausedAllSet' },
    { type: 'event', anonymous: false, inputs: [{ name: 'paused', internalType: 'bool', type: 'bool', indexed: false }], name: 'PausedDepositsSet' },
    {
        type: 'event',
        anonymous: false,
        inputs: [{ name: 'paused', internalType: 'bool', type: 'bool', indexed: false }],
        name: 'PausedUnlockYieldSet',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [{ name: 'paused', internalType: 'bool', type: 'bool', indexed: false }],
        name: 'PausedWithdrawalsSet',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'user', internalType: 'address', type: 'address', indexed: true },
            { name: 'winningAmount', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'usdPaid', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'RedeemedWinningForUSD',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'user', internalType: 'address', type: 'address', indexed: false },
            { name: 'finalizationTime', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'score', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'UserFinalized',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'user', internalType: 'address', type: 'address', indexed: true },
            { name: 'yesAmount', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'noAmount', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'Withdrawn',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'withdrawnThisCall', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'cumulativeWithdrawn', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'remainingInStrategy', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'YieldUnlockProgress',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'leftoverUsd', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'principalAtStart', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'YieldUnlockStarted',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'totalWithdrawnUsd', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'totalYield', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'userYield', internalType: 'uint256', type: 'uint256', indexed: false },
            { name: 'protocolYield', internalType: 'uint256', type: 'uint256', indexed: false },
        ],
        name: 'YieldUnlocked',
    },
    { type: 'error', inputs: [], name: 'AlreadyFinalized' },
    { type: 'error', inputs: [], name: 'AlreadyHarvested' },
    { type: 'error', inputs: [], name: 'DepositLimitExceeded' },
    { type: 'error', inputs: [], name: 'InsufficientAmounts' },
    {
        type: 'error',
        inputs: [
            { name: 'holding', internalType: 'uint256', type: 'uint256' },
            { name: 'needed', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'InsufficientUSD',
    },
    { type: 'error', inputs: [{ name: 'have', internalType: 'uint256', type: 'uint256' }], name: 'InsufficientUserNo' },
    { type: 'error', inputs: [{ name: 'have', internalType: 'uint256', type: 'uint256' }], name: 'InsufficientUserYes' },
    {
        type: 'error',
        inputs: [
            { name: 'needed', internalType: 'uint256', type: 'uint256' },
            { name: 'withdrawn', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'InsufficientWithdrawalUSD',
    },
    { type: 'error', inputs: [{ name: 'bps', internalType: 'uint256', type: 'uint256' }], name: 'InvalidBps' },
    { type: 'error', inputs: [], name: 'InvalidDataProvider' },
    { type: 'error', inputs: [], name: 'InvalidInitialization' },
    { type: 'error', inputs: [{ name: 'outcomeSlotCount', internalType: 'uint256', type: 'uint256' }], name: 'InvalidOutcomeSlotCount' },
    { type: 'error', inputs: [], name: 'InvalidPool' },
    { type: 'error', inputs: [], name: 'InvalidUnderlyingAsset' },
    { type: 'error', inputs: [], name: 'MarketAlreadyResolved' },
    { type: 'error', inputs: [], name: 'MarketNotResolved' },
    { type: 'error', inputs: [], name: 'NoYield' },
    { type: 'error', inputs: [], name: 'NotFinalized' },
    { type: 'error', inputs: [], name: 'NotInitializing' },
    { type: 'error', inputs: [{ name: 'owner', internalType: 'address', type: 'address' }], name: 'OwnableInvalidOwner' },
    { type: 'error', inputs: [{ name: 'account', internalType: 'address', type: 'address' }], name: 'OwnableUnauthorizedAccount' },
    { type: 'error', inputs: [], name: 'PausedAll' },
    { type: 'error', inputs: [], name: 'PausedDeposits' },
    { type: 'error', inputs: [], name: 'PausedUnlockYield' },
    { type: 'error', inputs: [], name: 'PausedWithdrawals' },
    { type: 'error', inputs: [], name: 'RedeemMismatch' },
    { type: 'error', inputs: [], name: 'ReentrancyGuardReentrantCall' },
    { type: 'error', inputs: [{ name: 'token', internalType: 'address', type: 'address' }], name: 'SafeERC20FailedOperation' },
    { type: 'error', inputs: [], name: 'UnderlyingAssetNotSupported' },
    { type: 'error', inputs: [], name: 'VaultAlreadyFinalized' },
    { type: 'error', inputs: [], name: 'VaultNotFinalized' },
    { type: 'error', inputs: [], name: 'YieldAlreadyUnlocked' },
    { type: 'error', inputs: [], name: 'YieldNotUnlocked' },
] as const;
