export const safeProxyFactoryAbi = [
    {
        type: 'constructor',
        inputs: [
            { name: '_masterCopy', internalType: 'address', type: 'address' },
            { name: '_fallbackHandler', internalType: 'address', type: 'address' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'proxy',
                internalType: 'contract GnosisSafe',
                type: 'address',
                indexed: false,
            },
            {
                name: 'owner',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
        ],
        name: 'ProxyCreation',
    },
    {
        type: 'function',
        inputs: [],
        name: 'CREATE_PROXY_TYPEHASH',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'DOMAIN_TYPEHASH',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'NAME',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'computeProxyAddress',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: 'paymentToken', internalType: 'address', type: 'address' },
            { name: 'payment', internalType: 'uint256', type: 'uint256' },
            {
                name: 'paymentReceiver',
                internalType: 'address payable',
                type: 'address',
            },
            {
                name: 'createSig',
                internalType: 'struct SafeProxyFactory.Sig',
                type: 'tuple',
                components: [
                    { name: 'v', internalType: 'uint8', type: 'uint8' },
                    { name: 'r', internalType: 'bytes32', type: 'bytes32' },
                    { name: 's', internalType: 'bytes32', type: 'bytes32' },
                ],
            },
        ],
        name: 'createProxy',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'domainSeparator',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'fallbackHandler',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getContractBytecode',
        outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
        name: 'getSalt',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        inputs: [],
        name: 'masterCopy',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'proxyCreationCode',
        outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
        stateMutability: 'pure',
    },
] as const;
